name: JTC Cats Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies and Start Server
      run: |
        cd server
        npm install
        npm start &
        sleep 5

    - name: Install Client Dependencies and Start Client
      run: |
        cd client
        npm install
        npm start
