name: JTC Cats Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies and Start Server
      run: |
        cd server
        npm install
        npm start
        # Add a command to wait for the server to start (e.g., using a sleep or wait-for script)

  test:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Install Client Dependencies and Start Client
      run: |
        cd client
        npm install
        npm start
